services:

  web-client:
    image: "ghcr.io/powertac/web-client:${WEB_CLIENT_VERSION}"
    command: "--proxy http://${HOST_IP}:${WEB_CLIENT_HOST_PORT}?"
    # TODO : add config via discovery.json to web-client
    volumes:
      - "./services.json:/opt/powertac/web-client/services.json"
    ports:
      - "${HOST_IP}:${WEB_CLIENT_HOST_PORT}:80"

  orchestrator:
    depends_on:
      orchestrator_db:
        condition: service_healthy
    image: "ghcr.io/powertac/orchestrator:${ORCHESTRATOR_VERSION}"
    volumes:
      - "./orchestrator.properties:/opt/powertac/orchestrator/application.properties"
      - "${ORCHESTRATOR_ROOT_PATH}:/var/opt/powertac"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${HOST_IP}:${ORCHESTRATOR_HOST_PORT}:80"
    environment:
      HOST_IP: "${HOST_IP}"
      WEATHER_SERVER_HOST_PORT: "${WEATHER_SERVER_HOST_PORT}"
      WEB_CLIENT_HOST_PORT: "${WEB_CLIENT_HOST_PORT}"
      ORCHESTRATOR_ROOT_PATH: "${ORCHESTRATOR_ROOT_PATH}"
      MYSQL_HOST: "orchestrator_db"
      MYSQL_PASSWORD: "${ORCHESTRATOR_DB_PASSWORD}"

  weather:
    depends_on:
      weather_db:
        condition: service_healthy
    image: "ghcr.io/powertac/weather-server:${WEATHER_SERVER_VERSION}"
    volumes:
      - "./weather-server.properties:/opt/powertac/weather-server/application.properties"
      - "${WEATHER_SEED_FILE}:/var/opt/powertac/weather.sql"
    ports:
      - "${HOST_IP}:${WEATHER_SERVER_HOST_PORT}:80"
    environment:
      MYSQL_HOST: "weather_db"
      MYSQL_PASSWORD: "${WEATHER_DB_PASSWORD}"

  orchestrator_db:
    image: "mariadb:${MARIADB_VERSION}"
    volumes:
      - "${ORCHESTRATOR_DB_STORAGE_PATH}:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: powertac_orchestrator
      MYSQL_USER: powertac_orchestrator
      MYSQL_PASSWORD: "${ORCHESTRATOR_DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    healthcheck:
      test: "/usr/bin/mysql -upowertac_orchestrator -p${ORCHESTRATOR_DB_PASSWORD} --execute \"USE powertac_orchestrator;\""
      start_period: 1m
      interval: 15s
      timeout: 1s
      retries: 10

  weather_db:
    image: "mariadb:${MARIADB_VERSION}"
    volumes:
      - "${WEATHER_DB_STORAGE_PATH}:/var/lib/mysql"
      - "${WEATHER_SEED_FILE}:/var/opt/powertac/weather.sql"
    command: ["--max_allowed_packet=100000000"]
    environment:
      MYSQL_DATABASE: powertac_weather
      MYSQL_USER: powertac_weather
      MYSQL_PASSWORD: "${WEATHER_DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    healthcheck:
      test: "/usr/bin/mysql -upowertac_weather -p${WEATHER_DB_PASSWORD} --execute \"USE powertac_weather;\""
      start_period: 1m
      interval: 15s
      timeout: 1s
      retries: 10